
import { Container } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Nostalgia Generator</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/icon-transparent.png' />
      </Head>
      
    </>
  );
};

export default Home;
